sudo: required
services:
  - docker

before_install:
  - docker build -t rafaelmeteoro/docker-workflow -f Dockerfile.dev .

# script:
#   - docker run rafaelmeteoro/docker-workflow npm run test -- --coverage

# deplayment to AWS configuration
# travis-ci has a predefined of different providers or hosting services
deploy:
  provider: elasticbeanstalk
  region: "us-east-2" # get from url - this is your local time
  app: "docker-react" # application name that you picked on AWS
  env: "DockerReact-env" # already written for you at the top
  bucket_name: "elasticbeanstalk-us-east-2-236016411011" # from s3 services
  bucket_path: "docker-react" # same as application name
  on:
    branch: master # means whenever pushed code to master start deploying to the cloud
  # add some API key that will give access to our account over to Travis-CI
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $SECRET_KEY
