sudo: required
services:
  - docker

before_install:
  - docker build -t rafaelmeteoro/docker-workflow -f Dockerfile.dev .

script:
  - docker run rafaelmeteoro/docker-workflow npm run test -- --coverage
