# from node image version 11.10.1 based on alpine base image
FROM node:11.10.1-alpine

# make the working directory to be root directory
WORKDIR '/app'

# copy the package.json file to the current image in the root directory
COPY package.json .

# install all the dependencies for the project
RUN npm install

# copy the new installed dependencies to the container that created during npm install
COPY . .

# finallty start the server.
CMD [ "npm", "run", "start" ]
